# NumPy for Array Operations

## 2 Array Construction and Indexing <a id="6.2-array-construction-and-indexing"/>

This section provides several useful functions to construct arrays, e.g., containing only ones or zeros.

In [1]:
import numpy as np

np.ones((3, 4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [2]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

We can use these functions to create arrays with arbitrary values, e.g., we can create an array containing the values 99 as follows.

In [3]:
np.zeros((3, 3)) + 99

array([[99., 99., 99.],
       [99., 99., 99.],
       [99., 99., 99.]])

Creating arrays of ones or zeros can also be useful as placeholder arrays, in cases where we do not want to use the initial values for computations right away. 

NumPy also has functions to create identity matrices and diagonal matrices as `ndarrays`. 

In [4]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
np.diag((1, 2, 3))

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

Two other very useful functions for creating sequences of numbers within a specified range are `arange` and `linspace`. NumPy's `arange` function follows the same syntax as Python's `range` function. If two arguments are provided, the first argument represents the start value and the second argument defines the stop value of a half-open interval.

In [6]:
np.arange(4, 10)

array([4, 5, 6, 7, 8, 9])

If we only provide a single argument, the default start value of 0 is assumed.

In [7]:
np.arange(5)

array([0, 1, 2, 3, 4])

Similar to Python's `range`, a third argument can be provided to define the *step* (the default step size is 1). For example, we can obtain an array of all values between 1 and 11 with 0.1 step as follows.

In [8]:
ary3 = np.arange(1., 11., 0.1)
ary3

array([ 1. ,  1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,
        2.1,  2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,
        3.2,  3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,
        4.3,  4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,
        5.4,  5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,
        6.5,  6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,
        7.6,  7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,
        8.7,  8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,
        9.8,  9.9, 10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8,
       10.9])

Note the shape of this array.

In [9]:
np.shape(ary3)

(100,)

The `linspace` function is especially useful if we want to create a number of evenly spaced values in a specified interval.

In [10]:
np.linspace(6., 25., num=5)

array([ 6.  , 10.75, 15.5 , 20.25, 25.  ])

### Array Indexing

Simple NumPy indexing and slicing work similar to Python lists, as in the following examples.

In [11]:
ary = np.array([1, 2, 3, 4])
ary[2]

3

Also, the same Python semantics apply to slicing operations. The following example shows how to fetch the first three elements in `ary`.

In [12]:
ary[0:3] 

array([1, 2, 3])

If we work with arrays that have more than one dimension or axis, we separate our indexing or slicing operations by commas as shown in the following examples.

In [13]:
ary = np.array([[1, 2, 3],
                [4, 5, 6]])

ary[0, -2] # first row, second from last element

2

In [14]:
ary[-1, -1] # lower right

6

In [15]:
ary[1, 1] # first row, second column

5

In [16]:
ary[:, 0] # entire first column

array([1, 4])

In [17]:
ary[:, :2] # first two columns

array([[1, 2],
       [4, 5]])