# Lecture 6 - NumPy for Array Operations

## 6.3 Array Math <a id="6.3-array-math"/>

One of the core features of NumPy that makes working with `ndarray` so efficient and convenient is **vectorization**. NumPy provides vectorized functions for performing element-wise operations implicitly via so-called *ufuncs* which is short for "universal functions".

There are more than 60 ufuncs available in NumPy; ufuncs are implemented in compiled C code and very fast and efficient compared to Python. 

To provide an example of a simple ufunc for element-wise addition, consider the following example, where we add a scalar 1 to each element in a nested Python list.

In [30]:
lst = [[1, 2, 3], 
       [4, 5, 6]] # 2d array

for row_idx, row_val in enumerate(lst):
    for col_idx, col_val in enumerate(row_val):
        lst[row_idx][col_idx] += 1
lst

[[2, 3, 4], [5, 6, 7]]

We can accomplish the same using NumPy's ufunc for element-wise scalar addition as shown below.

In [31]:
ary = np.array([[1, 2, 3], [4, 5, 6]])
ary = np.add(ary, 1) 
ary

array([[2, 3, 4],
       [5, 6, 7]])

For basic arithmetic operations we can use `add`, `subtract`, `divide`, `multiply`, `power`, and `exp` (exponential). However, NumPy uses operator overloading so that we can use mathematical operators (`+`, `-`, `/`, `*`, and `**`) directly.

In [32]:
np.add(ary, 1)

array([[3, 4, 5],
       [6, 7, 8]])

In [33]:
ary + 1

array([[3, 4, 5],
       [6, 7, 8]])

In [34]:
np.power(ary, 2)

array([[ 4,  9, 16],
       [25, 36, 49]], dtype=int32)

In [35]:
ary**2

array([[ 4,  9, 16],
       [25, 36, 49]])

NumPy also has implementations for other math operations, such as `sqrt` (square root), `log` (natural logarithm), and `log10` (base-10 logarithm).

In [36]:
np.sqrt(ary)

array([[1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131]])

Often, we want to compute the sum or product of array elements along a given axis. For this purpose, we can use the `reduce` operation. By default, `reduce` applies an operation along the first axis (`axis=0`). In the case of a two-dimensional array, we can think of the first axis as the rows of a matrix. Thus, adding up elements along rows yields the column sums of that matrix as shown below.

In [37]:
ary = np.array([[1, 2, 3], 
                [4, 5, 6]]) # rolling over the 1st axis, axis 0

np.add.reduce(ary, axis=0)

array([5, 7, 9])

To compute the row sums of the array above, we can specify `axis=1`.

In [38]:
np.add.reduce(ary, axis=1) # row sums

array([ 6, 15])

NumPy also provides functions for specific operations such as `product` and `sum`. For example, `sum(axis=0)` is equivalent to `add.reduce`.

In [39]:
ary.sum(axis=0) # column sums

array([5, 7, 9])

In [40]:
ary.sum(axis=1) # row sums

array([ 6, 15])

<img src="images/ufunc.png" width="600">

Note also that `product` and `sum` both compute the product or sum of the entire array if we do not specify an axis.

In [41]:
ary.sum()

21

Other useful ufuncs are:
    
- `np.mean` (computes arithmetic mean or average)
- `np.std` (computes the standard deviation)
- `np.var` (computes variance)
- `np.sort` (sorts an array)
- `np.argsort` (returns indices that would sort an array)
- `np.min` (returns the minimum value of an array)
- `np.max` (returns the maximum value of an array)
- `np.argmin` (returns the index of the minimum value)
- `np.argmax` (returns the index of the maximum value)
- `np.array_equal` (checks if two arrays have the same shape and elements)