# Lecture 6 - NumPy for Array Operations

## 6.4 Broadcasting <a id="6.4-broadcasting"/>

**Broadcasting** allows to perform vectorized operations between two arrays even if their dimensions do not match. 

In [42]:
ary1 = np.array([1, 2, 3])
ary1 + 1

array([2, 3, 4])

In [43]:
# this is equivalent to:
ary1 + np.array([1, 1, 1])

array([2, 3, 4])

<img src="images/broadcasting-1.png" width="500">

For example, we can add a one-dimensional to a two-dimensional array, where NumPy creates an implicit multidimensional grid from the one-dimensional array `ary1`.

In [44]:
ary2 = np.array([[4, 5, 6], 
                 [7, 8, 9]])

ary2 + ary1

array([[ 5,  7,  9],
       [ 8, 10, 12]])

<img src="images/broadcasting-2.png" width="500">

Using broadcasting in Python requires compatibility between the sizes of the arrays. For instance, if we try to add two arrays of sizes (3,3) and (2,2), Python will return an error.

In [45]:
np.ones((3,3)) + np.ones((2,2))

ValueError: operands could not be broadcast together with shapes (3,3) (2,2) 

### Advanced Indexing -- Memory Views and Copies

In the previous sections, we used basic indexing and slicing routines. It is important to note that basic integer-based indexing and slicing create so-called *views* of NumPy arrays in the memory. Working with views can be highly desirable since it avoids making unnecessary copies of arrays to save memory resources. To illustrate the concept of memory views, let's look at a simple example where we access the first row in an array, assign it to a variable, and modify that variable.

In [46]:
ary = np.array([[1, 2, 3],
                [4, 5, 6]])

first_row = ary[0, :]

In [47]:
first_row

array([1, 2, 3])

In [48]:
first_row += 99

In [49]:
first_row

array([100, 101, 102])

As expected, `first_row` was modified, now containing the original values in the first row incremented by 99.

Note, however, that the original array was modified as well. The reason for this is that `ary[0, :]` created a view of the first row in `ary`, and its elements were then incremented by 99. 

In [50]:
ary

array([[100, 101, 102],
       [  4,   5,   6]])

The same concept applies to slicing operations.

In [51]:
ary = np.array([[1, 2, 3],
                [4, 5, 6]])

last_col = ary[:, 2]
last_col += 99
ary

array([[  1,   2, 102],
       [  4,   5, 105]])

Therefore, it is important to be aware that indexing and slicing create views, which can speed up our code by avoiding to create unnecessary copies in memory. However, in certain scenarios we want to create a copy of an array; we can do this via the `copy` method as shown below.

In [52]:
ary = np.array([[1, 2, 3],
                [4, 5, 6]])

first_row = ary[0].copy()
first_row += 99

In [53]:
first_row

array([100, 101, 102])

In [54]:
ary

array([[1, 2, 3],
       [4, 5, 6]])

### Fancy Indexing

In addition to basic single-integer indexing and slicing operations, NumPy supports advanced indexing routines called *fancy indexing*. Via fancy indexing, we can use tuple or list objects of non-contiguous integer indices to return desired array elements. Since fancy indexing can be performed with non-contiguous sequences, it cannot return a view -- a contiguous slice from memory. Thus, fancy indexing always returns a copy of an array: it is important to keep that in mind. The following code snippets show some fancy indexing examples.

In [55]:
ary = np.array([[1, 2, 3],
                [4, 5, 6]])

ary[:, [0, 2]] # first and and last column

array([[1, 3],
       [4, 6]])

In [56]:
this_is_a_copy = ary[:, [0, 2]]
this_is_a_copy += 99

Note that the values in `this_is_a_copy` were incremented as expected.

In [57]:
this_is_a_copy

array([[100, 102],
       [103, 105]])

However, the contents of the original array remain unaffected.

In [58]:
ary

array([[1, 2, 3],
       [4, 5, 6]])

### Boolean Masks for Indexing

We can also use Boolean masks for indexing, that is, arrays of `True` and `False` values. Consider the following example, where we return all values in the array that are greater than 3.

In [59]:
ary = np.array([[1, 2, 3],
                [4, 5, 6]])

greater3_mask = ary > 3
greater3_mask

array([[False, False, False],
       [ True,  True,  True]])

Using these masks, we can select elements given our desired criteria.

In [60]:
ary[greater3_mask]

array([4, 5, 6])

Or, we can also write this as follows.

In [61]:
ary[ary>3]

array([4, 5, 6])

We can also chain different selection criteria using the logical *and* operator `&` or the logical *or* operator `|`. The example below demonstrates how we can select array elements that are greater than 3 and divisible by 2.

In [62]:
(ary > 3) & (ary % 2 == 0)

array([[False, False, False],
       [ True, False,  True]])

Similar to the previous example, we can use this boolean array as a mask for selecting the respective elements from the array.

In [63]:
ary[(ary > 3) & (ary % 2 == 0)]

array([4, 6])

And, for example, to negate a condition, we can use the `~` operator:

In [64]:
ary[~((ary < 2) | (ary > 4) )]

array([2, 3, 4])

A related, useful function to assign values to specific elements in an array is the `np.where` function. In the example below, we assign a 1 to all values in the array that are greater than 2, and 0 otherwise.

In [65]:
ary = np.array([1, 2, 3, 4, 5])

np.where(ary > 2, 1, 0)

array([0, 0, 1, 1, 1])