# Lecture 6 - NumPy for Array Operations

## 6.5 Random Number Generators <a id="6.5-random-number-generators"/>

In machine learning and data science, we often need to generate arrays of random numbers, such as the initial values of the model parameters. NumPy has a `random` subpackage to create random numbers and samples from a variety of distributions. 

Let's start with drawing a random sample of three numbers in the range [0,1] from a uniform distribution via `random.rand`.

In [4]:
np.random.rand(3)

array([0.85336891, 0.77772825, 0.33364941])

If we make another draw, we will obtain a different random sample. 

In [5]:
np.random.rand(3)

array([0.05802936, 0.42100879, 0.3124455 ])

Numpy also allows to use a fixed *random seed* for the  random number generator, and in that case, the random sample will be same at each draw. 

In [6]:
np.random.seed(seed=123)

np.random.rand(3)

array([0.69646919, 0.28613933, 0.22685145])

In [7]:
np.random.seed(seed=123)

np.random.rand(3)

array([0.69646919, 0.28613933, 0.22685145])

And, of course, if we change the random seed value, the generated random numbers will be also different.

In [8]:
np.random.seed(seed=43)

np.random.rand(3)

array([0.11505457, 0.60906654, 0.13339096])

Using a random seed is highly recommended in practical applications and in research projects, since it ensures that our results are reproducible, since using the same seed will create the same random numbers. 

We can also create  multi-dimensional arrays of random numbers, if needed.

In [9]:
np.random.rand(5,5)

array([[0.24058962, 0.32713906, 0.85913749, 0.66609021, 0.54116221],
       [0.02901382, 0.7337483 , 0.39495002, 0.80204712, 0.25442113],
       [0.05688494, 0.86664864, 0.221029  , 0.40498945, 0.31609647],
       [0.0766627 , 0.84322469, 0.84893915, 0.97146509, 0.38537691],
       [0.95448813, 0.44575836, 0.66972465, 0.08250005, 0.89709858]])

And, we can draw random numbers from other distributions. For instance, `random.randn` returns random numbers from a normal, i.e., Gaussian, distribution, with mean 0, and variance 1. 

In [10]:
np.random.randn(4)

array([-1.04683899, -0.88961759,  0.01404054, -0.16082969])

Or, for instance if we needed to generate 6 random values from a normal distribution with mean -3 and standard deviation 10, we can write as follows.

In [ ]:
-3 + 10*np.random.randn(6)

Also, it can be useful to create separate `RandomState` objects for various parts of our code, so that we can test methods in a reproducible manner. The example below shows how we can use a `RandomState` object to create the same results that we obtained via `np.random.rand` in the previous code.

In [11]:
rng2 = np.random.RandomState(seed=123)
rng2.rand(3)

array([0.69646919, 0.28613933, 0.22685145])

In the above code, `np.random.RandomState()` constructed a random number generator that we named `rng2`. When we call `rng2` to draw random numbers, it uses the specified seed (seed=123) to create random numbers in a controlled way. Note however that the seed 123 will be applied only to the `rng2` object, and it does not have effect on other freestanding functions in our code that use `np.random`. If we would like to apply the random seed 123 to all other  `np.random` functions in our code, we will need to explicitly request this with `np.random.seed(seed=123)`.