# Lecture 6 - NumPy for Array Operations

## 6.6 Reshaping NumPy Arrays <a id="6.6-reshaping-numpy-arrays"/>

In practice, we often run into situations where existing arrays do not have the *right* shape to perform certain computations. As you might remember from the beginning of this article, the size of NumPy arrays is fixed. Fortunately, this does not mean that we have to create new arrays and copy values from the old array to the new one if we want arrays of different shapes. That is, the size is fixed, but the shape is not. NumPy provides a `reshape` method that allows to obtain a view of an array with a different shape. 

For example, we can reshape a one-dimensional array into a two-dimensional one using `reshape` as follows.

In [12]:
ary1d = np.array([1, 2, 3, 4, 5, 6])
ary2d_view = ary1d.reshape(2, 3)
ary2d_view

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
np.may_share_memory(ary2d_view, ary1d)

True

The `True` value returned from `np.may_share_memory` indicates that the reshape operation returns a memory view, not a copy.

When using reshape, we need to make sure that the reshaped array has the same number of elements as the original one. Otherwise, we will obtain an error message.

In [14]:
ary2d_view1 = ary1d.reshape(3, 4)

ValueError: cannot reshape array of size 6 into shape (3,4)

However, we do not need to specify the number of elements in each axis. NumPy can figure out how many elements to put along an axis if only one axis is unspecified, by using the placeholder `-1`.

In [15]:
ary1d.reshape(-1, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

We can also use `reshape` to flatten an array.

In [16]:
ary = np.array([[[1, 2, 3],
                 [4, 5, 6]]])

ary.reshape(-1)

array([1, 2, 3, 4, 5, 6])

Other methods for flattening arrays exist, namely `flatten`, which creates a copy of the array, and `ravel`, which creates a memory view.

In [17]:
ary.flatten()

array([1, 2, 3, 4, 5, 6])

In [18]:
ary.ravel()

array([1, 2, 3, 4, 5, 6])

Sometimes, we are interested in merging different arrays. Unfortunately, there is no efficient way to do this without creating a new array, since NumPy arrays have a fixed size. While combining arrays should be avoided if possible for reasons of computational efficiency, it is sometimes necessary. To combine two or more array objects, we can use NumPy's `concatenate` function as shown in the following examples.

In [19]:
ary = np.array([[1, 2, 3]])

# stack along the first axis (here: rows)
np.concatenate((ary, ary), axis=0)

array([[1, 2, 3],
       [1, 2, 3]])

In [20]:
# stack along the second axis (here: columns)
np.concatenate((ary, ary), axis=1)

array([[1, 2, 3, 1, 2, 3]])

Two related functions are `vstack` and `hstack` that stand for vertically or horizontally stacking arrays, respectively. 

In [21]:
np.vstack((ary, ary))

array([[1, 2, 3],
       [1, 2, 3]])

In [22]:
np.hstack((ary, ary))

array([[1, 2, 3, 1, 2, 3]])