# Lecture 6 - NumPy for Array Operations

## 6.7 Linear Algebra with NumPy <a id="6.7-linear-algebra-with-numpy"/>

We can think of one-dimensional NumPy arrays as data structures that represent row vectors.

In [23]:
row_vector = np.array([1, 2, 3])
row_vector

array([1, 2, 3])

In [25]:
row_vector.shape

(3,)

Similarly, we can use two-dimensional arrays to create column vectors.

In [24]:
column_vector = np.array([1, 2, 3]).reshape(-1, 1)
column_vector

array([[1],
       [2],
       [3]])

In [26]:
column_vector.shape

(3, 1)

Instead of reshaping a one-dimensional array into a two-dimensional one, we can simply add a new axis as shown below.

In [27]:
row_vector[:, np.newaxis]

array([[1],
       [2],
       [3]])

To perform matrix multiplication between matrices, we know that number of columns of the left matrix must match the number of rows of the matrix to the right. In NumPy, we can perform matrix multiplication via the `matmul` function.

In [28]:
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])

In [29]:
np.matmul(matrix, column_vector)

array([[14],
       [32]])

<img src="images/matmul.png" width="300">

However, if we are working with matrices and vectors, NumPy can be quite forgiving if the dimensions of matrices and one-dimensional arrays do not match exactly -- thanks to broadcasting. The following example yields the same result as the matrix-column vector multiplication, except that it returns a one-dimensional array instead of a two-dimensional one.

In [30]:
np.matmul(matrix, row_vector)

array([14, 32])

Similarly, we can compute the dot-product between two vectors.

In [31]:
np.matmul(row_vector, row_vector)

14

NumPy has a special `dot` function that calculates the dot-product for one-dimensional arrays, and otherwise behaves similar to `matmul` on multi-dimensional arrays.

In [32]:
np.dot(matrix, row_vector)

array([14, 32])

Note that an even more convenient way for executing `np.dot` is using the `@` symbol with NumPy arrays.

In [33]:
matrix @ row_vector

array([14, 32])

NumPy also has a handy `transpose` method to transpose matrices.

In [34]:
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])

matrix.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

There is also a shorthand for `transpose` simply as `T`.

In [35]:
matrix.T

array([[1, 4],
       [2, 5],
       [3, 6]])

While this section demonstrates some of the basic linear algebra operations carried out on NumPy arrays that we use in practice, you can find additional functions in the documentation of NumPy's submodule for linear algebra: [`numpy.linalg`](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html). If you want to perform a particular linear algebra routine that is not implemented in NumPy, it is also worth consulting the [`scipy.linalg` documentation](https://docs.scipy.org/doc/scipy/reference/linalg.html) -- SciPy is a library for scientific computing built on top of NumPy.

One last note is that there is also a special [`matrix`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.html) type in NumPy. NumPy `matrix` objects are analogous to NumPy arrays but are restricted to two dimensions. Also, matrices define certain operations differently than arrays; for instance, the `*` operator performs matrix multiplication instead of element-wise multiplication. However, NumPy `matrix` is less popular in the science community compared to the more general array data structure. 

### Motivation for Using NumPy: It is Fast!

Let's compare computing a vector dot product in Python (using lists) and compare it with  NumPy's dot-product function. Mathematically, the dot product between two vectors $\mathbf{x}$ and $\mathbf{w}$ can be written as follows:

$$
z = \sum_i x_i w_i = x_1 \times w_1 + x_2 \times w_2 + ... + x_n \times w_n = \mathbf{x}^\top \mathbf{w} 
$$

First, the Python implementation using a for-loop.

In [36]:
def python_forloop_list_approach(x, w):
    z = 0.
    for i in range(len(x)):
        z += x[i] * w[i]
    return z


a = [1., 2., 3.]
b = [4., 5., 6.]

print(python_forloop_list_approach(a, b))

32.0


Let us compute the runtime for two larger (1000-element) vectors using IPython's `%timeit` magic function.

In [37]:
large_a = list(range(1000))
large_b = list(range(1000))


%timeit python_forloop_list_approach(large_a, large_b)

247 µs ± 60.7 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


Next, we use the `dot` function/method implemented in NumPy to compute the dot product between two vectors and run `%timeit` afterwards.

In [38]:
def numpy_dotproduct_approach(x, w):
    # same as np.dot(x, w)
    # and same as x @ w
    return x.dot(w)
    

a = np.array([1., 2., 3.])
b = np.array([4., 5., 6.])

print(numpy_dotproduct_approach(a, b))

32.0


In [39]:
large_a = np.arange(1000)
large_b = np.arange(1000)

%timeit numpy_dotproduct_approach(large_a, large_b)

2.32 µs ± 367 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


As we can see, replacing the for-loop with NumPy's dot function makes the computation of the vector dot product approximately 100 times faster.

[BACK TO TOP](#top)